version: '3.9'
services:
  db:
    image: 'edisonjpp/postgresql:postgresql'
    env_file:
      - .env
    ports:
      - 5432:5432
  cache:
    image: 'edisonjpp/redis:redis'
    env_file:
      - .env
    ports:
      - 6379:6379
